import type { GameDefinition } from './types';

export const GAMES_CATALOG: GameDefinition[] = [
  {
    id: 'manu-kart',
    slug: 'manu-kart',
    title: 'Manu Kart',
    tagline: 'Flagship 2D/3D highway kart racing with drift & powerups.',
    description: 'ManuPlay flagship racer! Outmaneuver rival AI karts, hit speed boosters, collect nitro cans, trigger powerups, and set record lap times across futuristic neon tracks.',
    category: 'Racing',
    tags: ['Flagship', 'Kart Racing', 'Drift', 'Nitro', 'Powerups', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #00f0ff 0%, #a855f7 100%)',
    coverImage: '/assets/games/manu-kart-cover.png',
    accentColor: '#00f0ff',
    iconName: 'Flame',
    rating: 5.0,
    plays: 285000,
    orientation: 'landscape',
    engine: 'canvas',
    loadEngine: () => import('./manu-kart/ManuKartGame').then(m => m.ManuKartGame),
    featured: true,
    trending: true,
    isNew: true,
    offlineSupported: true,
    multiplayerSupported: true,
    manuCoinsReward: 100,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['A / Left Arrow: Steer Left', 'D / Right Arrow: Steer Right', 'Space / W: Nitro Boost'],
      mobile: ['Left Touch Button: Turn Left', 'Right Touch Button: Turn Right', 'BOOST Button: Nitro']
    }
  },
  {
    id: 'chess',
    slug: 'chess',
    title: 'Chess Master',
    tagline: 'Classic chess with smart AI & local 2-player modes.',
    description: 'Challenge your mind with grandmaster strategy! Play against adaptive AI or duel a friend on the same screen with full move validation, blitz timers, and puzzle challenges.',
    category: 'Board',
    tags: ['Chess', 'Brain', 'AI Opponent', '2 Player', 'Offline', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #1e293b 0%, #475569 100%)',
    coverImage: '/assets/games/chess-cover.png',
    accentColor: '#38bdf8',
    iconName: 'Brain',
    rating: 4.9,
    plays: 195000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./chess/ChessGame').then(m => m.ChessGame),
    featured: true,
    trending: true,
    isNew: true,
    offlineSupported: true,
    multiplayerSupported: true,
    manuCoinsReward: 80,
    sessionLength: 'Medium (5-15 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['Click Chess Piece to select and click target square to move'],
      mobile: ['Tap Chess Piece to highlight valid moves and tap destination']
    }
  },
  {
    id: '8ball-pool',
    slug: '8ball-pool',
    title: '8 Ball Pool',
    tagline: 'Realistic physics cue ball pocketing challenge.',
    description: 'Master cue ball trajectory and spin! Drag back to aim, adjust power, and sink target balls into 6 pockets with realistic cushion reflection physics.',
    category: 'Sports',
    tags: ['Pool', 'Physics', 'Billiards', 'Aim Line', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #059669 0%, #064e3b 100%)',
    coverImage: '/assets/games/8ball-pool-cover.png',
    accentColor: '#10b981',
    iconName: 'Trophy',
    rating: 4.9,
    plays: 230000,
    orientation: 'landscape',
    engine: 'canvas',
    loadEngine: () => import('./8ball-pool/EightBallPoolGame').then(m => m.EightBallPoolGame),
    featured: true,
    trending: true,
    isNew: true,
    offlineSupported: true,
    multiplayerSupported: true,
    manuCoinsReward: 90,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['Click & Drag mouse backward from cue ball to aim and release to shoot'],
      mobile: ['Touch & Drag backward to adjust aim angle & power meter, then release']
    }
  },
  {
    id: 'trivia-battle',
    slug: 'trivia-battle',
    title: 'Trivia Battle',
    tagline: 'Real-time quiz across Gaming, Science, Tech & Sports.',
    description: 'Test your knowledge against the clock! Answer questions across popular categories, build answer streak multipliers, and earn massive XP rewards.',
    category: 'Trivia',
    tags: ['Quiz', 'Trivia', 'Brain Training', 'Streak Multiplier', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #f59e0b 0%, #ec4899 100%)',
    coverImage: '/assets/games/trivia-battle-cover.png',
    accentColor: '#f59e0b',
    iconName: 'Sparkles',
    rating: 4.8,
    plays: 162000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./trivia-battle/TriviaBattleGame').then(m => m.TriviaBattleGame),
    featured: true,
    trending: true,
    isNew: true,
    offlineSupported: true,
    multiplayerSupported: false,
    manuCoinsReward: 75,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Easy',
    controls: {
      desktop: ['Click option buttons A, B, C, D before the timer runs out'],
      mobile: ['Tap answer buttons A, B, C, D before time expires']
    }
  },
  {
    id: 'neon-drift',
    slug: 'neon-drift',
    title: 'Neon Drift',
    tagline: 'High-speed cyberpunk highway racing with instant nitro boosts.',
    description: 'Hit the neon-drenched highway at night! Dodge speeding traffic, collect energy power-ups, boost through speed traps, and see how long you can survive the endless drift.',
    category: 'Racing',
    tags: ['Cyberpunk', 'High Speed', 'Nitro', 'Highway', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #00f0ff 0%, #7000ff 100%)',
    coverImage: '/assets/games/neon-drift-cover.png',
    accentColor: '#00f0ff',
    iconName: 'Zap',
    rating: 4.9,
    plays: 142500,
    orientation: 'landscape',
    engine: 'canvas',
    loadEngine: () => import('./neon-drift/NeonDriftGame').then(m => m.NeonDriftGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 50,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['A / Left Arrow: Turn Left', 'D / Right Arrow: Turn Right', 'Space / W: Nitro Boost', 'S / Down: Brake'],
      mobile: ['Left Touch Button: Turn Left', 'Right Touch Button: Turn Right', 'BOOST Button: Nitro Speed', 'BRAKE Button: Slow down']
    }
  },
  {
    id: 'sky-runner',
    slug: 'sky-runner',
    title: 'Sky Runner',
    tagline: 'Leap across cyber platforms high above the clouds.',
    description: 'Precision endless platform runner set in a glowing futuristic skyline. Time your jumps and double jumps to scale floating platforms, collect plasma orbs, and avoid laser spikes!',
    category: 'Action',
    tags: ['Endless Runner', 'Platforms', 'Double Jump', 'Cyberpunk', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #ff007f 0%, #7928ca 100%)',
    accentColor: '#ff007f',
    iconName: 'Sparkles',
    rating: 4.8,
    plays: 98400,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./sky-runner/SkyRunnerGame').then(m => m.SkyRunnerGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 50,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['Space / W / Up Arrow: Jump (Press again for Double Jump)'],
      mobile: ['Tap Screen / JUMP Button: Jump & Double Jump']
    }
  },
  {
    id: 'zombie-survival',
    slug: 'zombie-survival',
    title: 'Zombie Survival',
    tagline: 'Top-down neon wave survival shooter.',
    description: 'Survive relentless waves of neon cyber-zombies in a localized arena! Move swiftly, manage your ammunition, collect health medkits, and clear every wave before you get overwhelmed.',
    category: 'Action',
    tags: ['Survival', 'Shooter', 'Zombie Waves', 'Arena', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #ffaa00 0%, #ff0055 100%)',
    coverImage: '/assets/games/zombie-survival-cover.png',
    accentColor: '#ffaa00',
    iconName: 'ShieldAlert',
    rating: 4.7,
    plays: 112000,
    orientation: 'landscape',
    engine: 'canvas',
    loadEngine: () => import('./zombie-survival/ZombieSurvivalGame').then(m => m.ZombieSurvivalGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 60,
    sessionLength: 'Medium (5-15 min)',
    difficulty: 'Hard',
    controls: {
      desktop: ['W, A, S, D / Arrows: Move character', 'Space / Left Click: Fire Laser Weapon'],
      mobile: ['Left Virtual Joystick / DPAD: Move', 'FIRE Touch Button: Shoot Laser']
    }
  },
  {
    id: 'block-puzzle',
    slug: 'block-puzzle',
    title: 'Block Puzzle',
    tagline: 'Addictive grid block placement & line clears.',
    description: 'Place geometric neon blocks on an 8x8 grid to complete full horizontal rows and vertical columns. Clear multiple lines simultaneously for massive combo multipliers!',
    category: 'Puzzle',
    tags: ['Grid Puzzle', 'Brain Teaser', 'Combo Clear', 'Relaxing', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #00ff88 0%, #0088ff 100%)',
    coverImage: '/assets/games/block-puzzle-cover.png',
    accentColor: '#00ff88',
    iconName: 'Grid',
    rating: 4.9,
    plays: 210000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./block-puzzle/BlockPuzzleGame').then(m => m.BlockPuzzleGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 40,
    sessionLength: 'Medium (5-15 min)',
    difficulty: 'Easy',
    controls: {
      desktop: ['Click & Drag Block: Place on Grid'],
      mobile: ['Touch Drag Block: Place on Grid cell']
    }
  },
  {
    id: 'space-shooter',
    slug: 'space-shooter',
    title: 'Space Shooter',
    tagline: 'Classic horizontal arcade galaxy defender.',
    description: 'Take command of the starship Alpha-1! Pilot through asteroid belts, destroy alien fighter squadrons, grab weapon upgrade power-ups, and defeat colossal mothership bosses.',
    category: 'Arcade',
    tags: ['Space Combat', 'Shmup', 'Boss Battles', 'Powerups', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #9900ff 0%, #00e5ff 100%)',
    accentColor: '#00e5ff',
    iconName: 'Rocket',
    rating: 4.8,
    plays: 165000,
    orientation: 'landscape',
    engine: 'canvas',
    loadEngine: () => import('./space-shooter/SpaceShooterGame').then(m => m.SpaceShooterGame),
    featured: false,
    trending: false,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 50,
    sessionLength: 'Medium (5-15 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['W, A, S, D / Arrow Keys: Move Ship', 'Space Key: Auto/Manual Laser Fire'],
      mobile: ['Touch & Drag Ship / Virtual Stick: Move & Shoot']
    }
  },
  {
    id: 'tower-defense',
    slug: 'tower-defense',
    title: 'Tower Defense',
    tagline: 'Strategic tactical defense against cyber creep waves.',
    description: 'Build and upgrade Laser Turrets, Plasma Cannons, and Frost Towers along the creep path to defend your central core. Manage your gold economy and survive boss waves!',
    category: 'Strategy',
    tags: ['Tower Defense', 'Strategy', 'Turrets', 'Creep Waves', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #7000ff 0%, #ff007f 100%)',
    accentColor: '#7000ff',
    iconName: 'ShieldAlert',
    rating: 4.9,
    plays: 87000,
    orientation: 'landscape',
    engine: 'canvas',
    loadEngine: () => import('./tower-defense/TowerDefenseGame').then(m => m.TowerDefenseGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 70,
    sessionLength: 'Long (15+ min)',
    difficulty: 'Hard',
    controls: {
      desktop: ['Click Road Grid Cell: Place Tower', 'Select Tower Type: Bottom Toolbar'],
      mobile: ['Tap Road Grid Cell: Place Tower', 'Tap Toolbar: Select Tower Type']
    }
  },
  {
    id: 'hoop-master',
    slug: 'hoop-master',
    title: 'Hoop Master',
    tagline: 'Precision basketball shooting & streak combo challenges.',
    description: 'Adjust your launch trajectory and shoot basketballs into moving hoops. Chain swish shots to multiply your streak bonus and earn extra shots!',
    category: 'Sports',
    tags: ['Basketball', 'Physics', 'Shooting', 'Streak Combo', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #ff6600 0%, #ffaa00 100%)',
    accentColor: '#ff6600',
    iconName: 'Trophy',
    rating: 4.7,
    plays: 74000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./hoop-master/HoopMasterGame').then(m => m.HoopMasterGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 40,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Easy',
    controls: {
      desktop: ['Up / Down Arrows: Adjust Trajectory Angle', 'Space Key / Click: Shoot Ball'],
      mobile: ['Tap Screen: Shoot Ball towards Target']
    }
  },
  {
    id: 'cyber-memory',
    slug: 'cyber-memory',
    title: 'Cyber Memory',
    tagline: 'Brain training icon matching against the clock.',
    description: 'Flip glowing neon cards to match identical cyber icons on a 4x4 grid before time runs out. Test and improve your memory focus!',
    category: 'Puzzle',
    tags: ['Memory Match', 'Brain Training', 'Cards', 'Time Attack', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #00ff88 0%, #9900ff 100%)',
    accentColor: '#00ff88',
    iconName: 'Grid',
    rating: 4.8,
    plays: 92000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./cyber-memory/CyberMemoryGame').then(m => m.CyberMemoryGame),
    featured: false,
    trending: false,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 35,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Easy',
    controls: {
      desktop: ['Click Card: Flip & Match'],
      mobile: ['Tap Card: Flip & Match']
    }
  },
  {
    id: 'neon-wings',
    slug: 'neon-wings',
    title: 'Neon Wings',
    tagline: 'Flap through glowing cyber portals in deep space.',
    description: 'Precision timing wing runner! Tap to flap your cyber wings upward and guide your character through narrow glowing plasma gates.',
    category: 'Arcade',
    tags: ['Wing Flap', 'Precision', 'Arcade', 'Portal Gates', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #ff007f 0%, #00f0ff 100%)',
    accentColor: '#ff007f',
    iconName: 'Sparkles',
    rating: 4.6,
    plays: 68000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./neon-wings/NeonWingsGame').then(m => m.NeonWingsGame),
    featured: false,
    trending: false,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 40,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Hard',
    controls: {
      desktop: ['Space Key / Up Arrow / Click: Flap Wings Up'],
      mobile: ['Tap Screen: Flap Wings Up']
    }
  },
  {
    id: 'traffic-rush',
    slug: 'traffic-rush',
    title: 'Traffic Rush 3D',
    tagline: '3D perspective highway lane switcher with nitro speed.',
    description: 'Shift lanes at 200 KM/H on a glowing 3D perspective highway! Dodge oncoming traffic obstacles, trigger nitro boosts, and climb the speed leaderboard.',
    category: 'Racing',
    tags: ['3D Racing', 'Highway', 'Lane Shift', 'Nitro', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #00f0ff 0%, #ff0055 100%)',
    accentColor: '#00f0ff',
    iconName: 'Zap',
    rating: 4.9,
    plays: 125000,
    orientation: 'landscape',
    engine: 'canvas',
    loadEngine: () => import('./traffic-rush/TrafficRushGame').then(m => m.TrafficRushGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 50,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['A / Left Arrow: Shift Left Lane', 'D / Right Arrow: Shift Right Lane', 'Space / W: Nitro Boost'],
      mobile: ['Left Touch Button: Shift Left', 'Right Touch Button: Shift Right', 'BOOST Button: Nitro']
    }
  },
  {
    id: 'color-sort',
    slug: 'color-sort',
    title: 'Color Sort Puzzle',
    tagline: 'Satisfying liquid tube color sorting brain teaser.',
    description: 'Pour colored liquid between test tubes until every tube is filled with a single solid color! Plan your moves carefully and solve progressively harder levels.',
    category: 'Casual',
    tags: ['Color Sort', 'Puzzle', 'Brain Teaser', 'Relaxing', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #ff0055 0%, #00f0ff 100%)',
    accentColor: '#ff0055',
    iconName: 'Smile',
    rating: 4.9,
    plays: 184000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./color-sort/ColorSortGame').then(m => m.ColorSortGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 35,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Easy',
    controls: {
      desktop: ['Click Tube: Select / Pour liquid into destination tube'],
      mobile: ['Tap Tube: Select & Pour colored liquid']
    }
  },
  {
    id: 'dual-arena',
    slug: 'dual-arena',
    title: 'Dual Arena Combat',
    tagline: 'Fast-paced local 2-player arena battle on a single screen.',
    description: 'Face off against a friend on the same device! Dodge incoming plasma shots, aim your lasers, and destroy your rival hero in intense split-screen combat.',
    category: '2 Player',
    tags: ['2-Player', 'Local Versus', 'Arena Combat', 'Duels', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #00f0ff 0%, #ff007f 100%)',
    accentColor: '#ff007f',
    iconName: 'Swords',
    rating: 4.8,
    plays: 142000,
    orientation: 'landscape',
    engine: 'canvas',
    loadEngine: () => import('./dual-arena/DualArenaGame').then(m => m.DualArenaGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    multiplayerSupported: true,
    manuCoinsReward: 60,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['P1: W, A, S, D + Space to Shoot', 'P2: Arrow Keys + Enter to Shoot'],
      mobile: ['P1: Tap Left Side to Shoot', 'P2: Tap Right Side to Shoot']
    }
  },
  {
    id: 'mini-golf',
    slug: 'mini-golf',
    title: 'Neon Mini Golf',
    tagline: 'Precision drag-to-aim mini golf course challenge.',
    description: 'Line up your shots and sink golf balls across neon obstacle courses! Dodge moving barriers, time your power meter, and score under par.',
    category: 'Sports',
    tags: ['Mini Golf', 'Physics', 'Drag Aim', 'Obstacles', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #00ff88 0%, #0088ff 100%)',
    accentColor: '#00ff88',
    iconName: 'Trophy',
    rating: 4.9,
    plays: 156000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./mini-golf/MiniGolfGame').then(m => m.MiniGolfGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 45,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['Click & Drag Ball Backwards: Aim & Adjust Power', 'Release: Shoot Golf Ball'],
      mobile: ['Touch & Drag Ball Backwards: Aim & Adjust Power', 'Release Touch: Shoot Ball']
    }
  },
  {
    id: 'cricket-smash',
    slug: 'cricket-smash',
    title: 'Cricket Smash',
    tagline: 'Mobile-first neon cricket batting challenge.',
    description: 'Timing is everything! Time your shots precisely as bowler delivers speedballs, spin, and yorkers. Smash 4s and 6s across 2 overs!',
    category: 'Sports',
    tags: ['Cricket', 'Batting', 'Timing', 'Sports', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #00ff88 0%, #00f0ff 100%)',
    coverImage: '/assets/games/cricket-smash-cover.png',
    accentColor: '#00ff88',
    iconName: 'Trophy',
    rating: 4.9,
    plays: 210000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./cricket-smash/CricketSmashGame').then(m => m.CricketSmashGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 50,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['Space / Click / Arrow Up: Time Batting Shot'],
      mobile: ['Tap Screen when ball crosses timing line']
    }
  },
  {
    id: 'penalty-shootout',
    slug: 'penalty-shootout',
    title: 'Penalty Shootout',
    tagline: 'Swipe and curve football penalty shots past AI keeper.',
    description: 'Step up to the penalty spot! Swipe and curve precision football shots into top goal corners past an agile goalkeeper.',
    category: 'Sports',
    tags: ['Football', 'Penalty', 'Soccer', 'Sports', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #ff0055 0%, #ffaa00 100%)',
    accentColor: '#ff0055',
    iconName: 'Trophy',
    rating: 4.8,
    plays: 198000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./penalty-shootout/PenaltyShootoutGame').then(m => m.PenaltyShootoutGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 45,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Easy',
    controls: {
      desktop: ['Click & Drag Ball Upwards to Shoot'],
      mobile: ['Swipe / Drag Ball Upwards toward goal corner']
    }
  },
  {
    id: 'number-merge',
    slug: 'number-merge',
    title: 'Number Merge 2048',
    tagline: '2048-style grid tile merge puzzle across 100 levels.',
    description: 'Merge matching numbers to reach 2048 and beyond! Swipe or use arrow keys to slide tiles across grid boards with obstacles.',
    category: 'Puzzle',
    tags: ['2048', 'Numbers', 'Puzzle', 'Brain', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%)',
    accentColor: '#3b82f6',
    iconName: 'Puzzle',
    rating: 4.9,
    plays: 145000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./number-merge/NumberMergeGame').then(m => m.NumberMergeGame),
    featured: true,
    trending: true,
    isNew: true,
    offlineSupported: true,
    manuCoinsReward: 60,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    totalLevels: 100,
    hasLevels: true,
    levelType: 'procedural',
    controls: {
      desktop: ['Arrow Keys / WASD: Slide Grid Tiles'],
      mobile: ['Swipe Up / Down / Left / Right on screen']
    }
  },
  {
    id: 'stack-tower',
    slug: 'stack-tower',
    title: 'Stack Tower',
    tagline: 'Precision block stacker with slicing physics.',
    description: 'Time your drops to stack moving blocks into high sky towers! Perfect timing triggers streak multipliers.',
    category: 'Arcade',
    tags: ['Stack', 'Precision', 'Arcade', 'Timing', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #00f0ff 0%, #ec4899 100%)',
    coverImage: '/assets/games/stack-tower-cover.png',
    accentColor: '#00f0ff',
    iconName: 'Gamepad2',
    rating: 4.8,
    plays: 128000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./stack-tower/StackTowerGame').then(m => m.StackTowerGame),
    featured: true,
    trending: true,
    isNew: true,
    offlineSupported: true,
    manuCoinsReward: 50,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    totalLevels: 100,
    hasLevels: true,
    levelType: 'procedural',
    controls: {
      desktop: ['Space / Click: Drop Moving Block'],
      mobile: ['Tap Screen to drop block onto tower']
    }
  },
  {
    id: 'blade-master',
    slug: 'blade-master',
    title: 'Blade Master',
    tagline: 'Precision knife throw arcade challenge.',
    description: 'Throw blades into rotating neon targets without hitting existing knives! Outsmart reversing rotation speeds.',
    category: 'Arcade',
    tags: ['Knife', 'Precision', 'Target', 'Arcade', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #f43f5e 0%, #f97316 100%)',
    accentColor: '#f43f5e',
    iconName: 'Gamepad2',
    rating: 4.9,
    plays: 165000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./blade-master/BladeMasterGame').then(m => m.BladeMasterGame),
    featured: true,
    trending: true,
    isNew: true,
    offlineSupported: true,
    manuCoinsReward: 55,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Hard',
    totalLevels: 100,
    hasLevels: true,
    levelType: 'procedural',
    controls: {
      desktop: ['Space / Click: Throw Knife at Target'],
      mobile: ['Tap Screen to launch blade']
    }
  },
  {
    id: 'tile-match',
    slug: 'tile-match',
    title: 'Tile Match 3D',
    tagline: 'Triple mahjong tile matching puzzle.',
    description: 'Pick 3 identical tiles into your holding tray to clear the board! Solve 100 stacked puzzle levels.',
    category: 'Puzzle',
    tags: ['Mahjong', 'Tile Match', 'Puzzle', 'Brain', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #10b981 0%, #06b6d4 100%)',
    accentColor: '#10b981',
    iconName: 'Puzzle',
    rating: 4.8,
    plays: 139000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./tile-match/TileMatchGame').then(m => m.TileMatchGame),
    featured: false,
    trending: true,
    isNew: true,
    offlineSupported: true,
    manuCoinsReward: 50,
    sessionLength: 'Medium (5-15 min)',
    difficulty: 'Medium',
    totalLevels: 100,
    hasLevels: true,
    levelType: 'handcrafted',
    controls: {
      desktop: ['Click Tiles to add to bottom matching tray'],
      mobile: ['Tap Tiles to collect and match 3']
    }
  },
  {
    id: 'color-switch',
    slug: 'color-switch',
    title: 'Color Switch',
    tagline: 'Obstacle color matching bounce arcade game.',
    description: 'Bounce glowing ball through rotating multi-colored shapes that match the ball color!',
    category: 'Arcade',
    tags: ['Color Match', 'Bounce', 'Arcade', 'Action', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%)',
    accentColor: '#ec4899',
    iconName: 'Gamepad2',
    rating: 4.7,
    plays: 112000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./color-switch/ColorSwitchGame').then(m => m.ColorSwitchGame),
    featured: false,
    trending: false,
    isNew: true,
    offlineSupported: true,
    manuCoinsReward: 45,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Hard',
    totalLevels: 100,
    hasLevels: true,
    levelType: 'procedural',
    controls: {
      desktop: ['Space / Click: Bounce Ball Upward'],
      mobile: ['Tap Screen to bounce ball']
    }
  },
  {
    id: 'word-connect',
    slug: 'word-connect',
    title: 'Word Connect',
    tagline: 'Swipe letter wheel word search spelling puzzle.',
    description: 'Swipe letter circles to spell valid hidden words and fill crossword grids across 100 levels!',
    category: 'Puzzle',
    tags: ['Word', 'Spelling', 'Puzzle', 'Brain', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #f59e0b 0%, #ef4444 100%)',
    accentColor: '#f59e0b',
    iconName: 'Puzzle',
    rating: 4.9,
    plays: 148000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./word-connect/WordConnectGame').then(m => m.WordConnectGame),
    featured: true,
    trending: true,
    isNew: true,
    offlineSupported: true,
    manuCoinsReward: 60,
    sessionLength: 'Medium (5-15 min)',
    difficulty: 'Easy',
    totalLevels: 100,
    hasLevels: true,
    levelType: 'handcrafted',
    controls: {
      desktop: ['Click & Drag connecting letters on circle wheel'],
      mobile: ['Swipe connecting letter nodes to spell words']
    }
  },
  {
    id: 'brick-breaker',
    slug: 'brick-breaker',
    title: 'Brick Breaker Neon',
    tagline: 'Neon paddle brick crusher with multi-ball powerups.',
    description: 'Bounce laser balls off your paddle to smash neon bricks! Collect multi-ball and fire powerups.',
    category: 'Arcade',
    tags: ['Brick Breaker', 'Paddle', 'Arcade', 'Retro', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #00f0ff 0%, #3b82f6 100%)',
    accentColor: '#00f0ff',
    iconName: 'Gamepad2',
    rating: 4.8,
    plays: 122000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./brick-breaker/BrickBreakerGame').then(m => m.BrickBreakerGame),
    featured: false,
    trending: true,
    isNew: true,
    offlineSupported: true,
    manuCoinsReward: 50,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    totalLevels: 100,
    hasLevels: true,
    levelType: 'procedural',
    controls: {
      desktop: ['Arrow Keys / A & D: Move Paddle Left / Right'],
      mobile: ['Drag finger along bottom to steer paddle']
    }
  },
  {
    id: 'fruit-slice',
    slug: 'fruit-slice',
    title: 'Fruit Carver Arcade',
    tagline: 'Reflex fruit slicing arcade game with combo streaks.',
    description: 'Swipe across canvas to slice flying neon fruits while avoiding explosive red bombs!',
    category: 'Arcade',
    tags: ['Fruit Slice', 'Reflex', 'Arcade', 'Action', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #84cc16 0%, #10b981 100%)',
    coverImage: '/assets/games/fruit-slice-cover.png',
    accentColor: '#84cc16',
    iconName: 'Gamepad2',
    rating: 4.9,
    plays: 175000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./fruit-slice/FruitSliceGame').then(m => m.FruitSliceGame),
    featured: true,
    trending: true,
    isNew: true,
    offlineSupported: true,
    manuCoinsReward: 55,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    totalLevels: 100,
    hasLevels: true,
    levelType: 'procedural',
    controls: {
      desktop: ['Click & Drag mouse across fruits to slice'],
      mobile: ['Swipe finger across screen to cut flying fruits']
    }
  },
  {
    id: 'bubble-shooter',
    slug: 'bubble-shooter',
    title: 'Bubble Shooter',
    tagline: 'Match-3 bubble cannon cluster pop puzzle.',
    description: 'Aim cannon and shoot colored bubbles to match 3 or more! Clear all bubbles before ammo runs out.',
    category: 'Puzzle',
    tags: ['Bubble Shooter', 'Match 3', 'Puzzle', 'Arcade', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #06b6d4 0%, #3b82f6 100%)',
    accentColor: '#06b6d4',
    iconName: 'Puzzle',
    rating: 4.9,
    plays: 188000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./bubble-shooter/BubbleShooterGame').then(m => m.BubbleShooterGame),
    featured: true,
    trending: true,
    isNew: true,
    offlineSupported: true,
    manuCoinsReward: 60,
    sessionLength: 'Medium (5-15 min)',
    difficulty: 'Medium',
    totalLevels: 100,
    hasLevels: true,
    levelType: 'procedural',
    controls: {
      desktop: ['Move mouse to aim cannon, Click to fire bubble'],
      mobile: ['Drag to aim cannon trajectory, Release to shoot']
    }
  },
  {
    id: 'maze-escape',
    slug: 'maze-escape',
    title: 'Maze Escape',
    tagline: 'Procedural neon maze runner puzzle with light energy.',
    description: 'Guide glowing cyber orb through dark procedurally generated mazes before energy runs out!',
    category: 'Puzzle',
    tags: ['Maze', 'Escape', 'Puzzle', 'Light', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #10b981 0%, #eab308 100%)',
    accentColor: '#10b981',
    iconName: 'Puzzle',
    rating: 4.8,
    plays: 105000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./maze-escape/MazeEscapeGame').then(m => m.MazeEscapeGame),
    featured: false,
    trending: false,
    isNew: true,
    offlineSupported: true,
    manuCoinsReward: 50,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Hard',
    totalLevels: 100,
    hasLevels: true,
    levelType: 'procedural',
    controls: {
      desktop: ['Arrow Keys / WASD: Guide orb through maze'],
      mobile: ['Swipe directionally to move orb through paths']
    }
  },
  {
    id: 'car-dodge',
    slug: 'car-dodge',
    title: 'Traffic Car Dodge',
    tagline: 'Multi-lane highway vehicle dodge race.',
    description: 'Steer your racer across highway lanes to dodge speeding traffic and police chases!',
    category: 'Racing',
    tags: ['Traffic', 'Car Dodge', 'Racing', 'Highway', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #f97316 0%, #ef4444 100%)',
    accentColor: '#f97316',
    iconName: 'Flame',
    rating: 4.8,
    plays: 142000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./car-dodge/CarDodgeGame').then(m => m.CarDodgeGame),
    featured: true,
    trending: true,
    isNew: true,
    offlineSupported: true,
    manuCoinsReward: 55,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    totalLevels: 100,
    hasLevels: true,
    levelType: 'procedural',
    controls: {
      desktop: ['Arrow Left / Right / A & D: Switch Highway Lanes'],
      mobile: ['Tap Left / Right side of screen to switch lanes']
    }
  },
  {
    id: 'reflex-tap',
    slug: 'reflex-tap',
    title: 'Reflex Tap Challenge',
    tagline: 'Fast-paced neon node sequence reaction game.',
    description: 'Tap glowing neon nodes as they light up in rapid sequence before timers expire! Avoid hazard nodes.',
    category: 'Casual',
    tags: ['Reflex', 'Reaction', 'Casual', 'Speed', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #00f0ff 0%, #f43f5e 100%)',
    accentColor: '#00f0ff',
    iconName: 'Smile',
    rating: 4.7,
    plays: 98000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./reflex-tap/ReflexTapGame').then(m => m.ReflexTapGame),
    featured: false,
    trending: false,
    isNew: true,
    offlineSupported: true,
    manuCoinsReward: 45,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    totalLevels: 100,
    hasLevels: true,
    levelType: 'procedural',
    controls: {
      desktop: ['Click glowing active nodes before timer expires'],
      mobile: ['Tap glowing nodes rapidly']
    }
  }
];

export const CATEGORIES_LIST: Array<{ name: string; slug: string; iconName: string; count: number; bgGradient: string }> = [
  { name: 'Racing', slug: 'racing', iconName: 'Flame', count: 4, bgGradient: 'from-cyan-500 to-blue-600' },
  { name: 'Action', slug: 'action', iconName: 'Swords', count: 2, bgGradient: 'from-pink-500 to-purple-600' },
  { name: 'Puzzle', slug: 'puzzle', iconName: 'Puzzle', count: 8, bgGradient: 'from-emerald-400 to-teal-600' },
  { name: 'Sports', slug: 'sports', iconName: 'Trophy', count: 5, bgGradient: 'from-amber-400 to-orange-600' },
  { name: 'Board', slug: 'board', iconName: 'Brain', count: 1, bgGradient: 'from-indigo-500 to-purple-600' },
  { name: 'Trivia', slug: 'trivia', iconName: 'Sparkles', count: 1, bgGradient: 'from-fuchsia-500 to-pink-600' },
  { name: '2 Player', slug: '2-player', iconName: 'Swords', count: 2, bgGradient: 'from-purple-600 to-pink-600' },
  { name: 'Arcade', slug: 'arcade', iconName: 'Gamepad2', count: 7, bgGradient: 'from-violet-500 to-indigo-600' },
  { name: 'Strategy', slug: 'strategy', iconName: 'Brain', count: 1, bgGradient: 'from-purple-600 to-pink-600' },
  { name: 'Casual', slug: 'casual', iconName: 'Smile', count: 2, bgGradient: 'from-fuchsia-500 to-pink-600' }
];
