import type { GameDefinition } from './types';

export const GAMES_CATALOG: GameDefinition[] = [
  {
    id: 'neon-drift',
    slug: 'neon-drift',
    title: 'Neon Drift',
    tagline: 'High-speed cyberpunk highway racing with instant nitro boosts.',
    description: 'Hit the neon-drenched highway at night! Dodge speeding traffic, collect energy power-ups, boost through speed traps, and see how long you can survive the endless drift.',
    category: 'Racing',
    tags: ['Cyberpunk', 'High Speed', 'Nitro', 'Highway', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #00f0ff 0%, #7000ff 100%)',
    accentColor: '#00f0ff',
    iconName: 'Zap',
    rating: 4.9,
    plays: 142500,
    orientation: 'landscape',
    engine: 'canvas',
    featured: true,
    trending: true,
    isNew: false,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['A / Left Arrow: Turn Left', 'D / Right Arrow: Turn Right', 'Space / W: Nitro Boost', 'S / Down: Brake'],
      mobile: ['Left Touch Button: Turn Left', 'Right Touch Button: Turn Right', 'BOOST Button: Nitro Speed', 'BRAKE Button: Slow down']
    }
  },
  {
    id: 'sky-runner',
    slug: 'sky-runner',
    title: 'Sky Runner',
    tagline: 'Leap across cyber platforms high above the clouds.',
    description: 'Precision endless platform runner set in a glowing futuristic skyline. Time your jumps and double jumps to scale floating platforms, collect plasma orbs, and avoid laser spikes!',
    category: 'Action',
    tags: ['Endless Runner', 'Platforms', 'Double Jump', 'Cyberpunk', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #ff007f 0%, #7928ca 100%)',
    accentColor: '#ff007f',
    iconName: 'Sparkles',
    rating: 4.8,
    plays: 98400,
    orientation: 'portrait',
    engine: 'canvas',
    featured: true,
    trending: true,
    isNew: false,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['Space / W / Up Arrow: Jump (Press again for Double Jump)'],
      mobile: ['Tap Screen / JUMP Button: Jump & Double Jump']
    }
  },
  {
    id: 'zombie-survival',
    slug: 'zombie-survival',
    title: 'Zombie Survival',
    tagline: 'Top-down neon wave survival shooter.',
    description: 'Survive relentless waves of neon cyber-zombies in a localized arena! Move swiftly, manage your ammunition, collect health medkits, and clear every wave before you get overwhelmed.',
    category: 'Action',
    tags: ['Survival', 'Shooter', 'Zombie Waves', 'Arena', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #ffaa00 0%, #ff0055 100%)',
    accentColor: '#ffaa00',
    iconName: 'ShieldAlert',
    rating: 4.7,
    plays: 112000,
    orientation: 'landscape',
    engine: 'canvas',
    featured: false,
    trending: true,
    isNew: false,
    sessionLength: 'Medium (5-15 min)',
    difficulty: 'Hard',
    controls: {
      desktop: ['W, A, S, D / Arrows: Move character', 'Space / Left Click: Fire Laser Weapon'],
      mobile: ['Left Virtual Joystick / DPAD: Move', 'FIRE Touch Button: Shoot Laser']
    }
  },
  {
    id: 'block-puzzle',
    slug: 'block-puzzle',
    title: 'Block Puzzle',
    tagline: 'Addictive grid block placement & line clears.',
    description: 'Place geometric neon blocks on an 8x8 grid to complete full horizontal rows and vertical columns. Clear multiple lines simultaneously for massive combo multipliers!',
    category: 'Puzzle',
    tags: ['Grid Puzzle', 'Brain Teaser', 'Combo Clear', 'Relaxing', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #00ff88 0%, #0088ff 100%)',
    accentColor: '#00ff88',
    iconName: 'Grid',
    rating: 4.9,
    plays: 210000,
    orientation: 'portrait',
    engine: 'canvas',
    featured: true,
    trending: true,
    isNew: false,
    sessionLength: 'Medium (5-15 min)',
    difficulty: 'Easy',
    controls: {
      desktop: ['Click & Drag Block: Place on Grid'],
      mobile: ['Touch Drag Block: Place on Grid cell']
    }
  },
  {
    id: 'space-shooter',
    slug: 'space-shooter',
    title: 'Space Shooter',
    tagline: 'Classic horizontal arcade galaxy defender.',
    description: 'Take command of the starship Alpha-1! Pilot through asteroid belts, destroy alien fighter squadrons, grab weapon upgrade power-ups, and defeat colossal mothership bosses.',
    category: 'Arcade',
    tags: ['Space Combat', 'Shmup', 'Boss Battles', 'Powerups', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #9900ff 0%, #00e5ff 100%)',
    accentColor: '#00e5ff',
    iconName: 'Rocket',
    rating: 4.8,
    plays: 165000,
    orientation: 'landscape',
    engine: 'canvas',
    featured: false,
    trending: false,
    isNew: false,
    sessionLength: 'Medium (5-15 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['W, A, S, D / Arrow Keys: Move Ship', 'Space Key: Auto/Manual Laser Fire'],
      mobile: ['Touch & Drag Ship / Virtual Stick: Move & Shoot']
    }
  },
  {
    id: 'tower-defense',
    slug: 'tower-defense',
    title: 'Tower Defense',
    tagline: 'Strategic tactical defense against cyber creep waves.',
    description: 'Build and upgrade Laser Turrets, Plasma Cannons, and Frost Towers along the creep path to defend your central core. Manage your gold economy and survive boss waves!',
    category: 'Strategy',
    tags: ['Tower Defense', 'Strategy', 'Turrets', 'Creep Waves', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #7000ff 0%, #ff007f 100%)',
    accentColor: '#7000ff',
    iconName: 'ShieldAlert',
    rating: 4.9,
    plays: 87000,
    orientation: 'landscape',
    engine: 'canvas',
    featured: true,
    trending: true,
    isNew: true,
    sessionLength: 'Long (15+ min)',
    difficulty: 'Hard',
    controls: {
      desktop: ['Click Road Grid Cell: Place Tower', 'Select Tower Type: Bottom Toolbar'],
      mobile: ['Tap Road Grid Cell: Place Tower', 'Tap Toolbar: Select Tower Type']
    }
  },
  {
    id: 'hoop-master',
    slug: 'hoop-master',
    title: 'Hoop Master',
    tagline: 'Precision basketball shooting & streak combo challenges.',
    description: 'Adjust your launch trajectory and shoot basketballs into moving hoops. Chain swish shots to multiply your streak bonus and earn extra shots!',
    category: 'Sports',
    tags: ['Basketball', 'Physics', 'Shooting', 'Streak Combo', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #ff6600 0%, #ffaa00 100%)',
    accentColor: '#ff6600',
    iconName: 'Trophy',
    rating: 4.7,
    plays: 74000,
    orientation: 'portrait',
    engine: 'canvas',
    featured: false,
    trending: true,
    isNew: true,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Easy',
    controls: {
      desktop: ['Up / Down Arrows: Adjust Trajectory Angle', 'Space Key / Click: Shoot Ball'],
      mobile: ['Tap Screen: Shoot Ball towards Target']
    }
  },
  {
    id: 'cyber-memory',
    slug: 'cyber-memory',
    title: 'Cyber Memory',
    tagline: 'Brain training icon matching against the clock.',
    description: 'Flip glowing neon cards to match identical cyber icons on a 4x4 grid before time runs out. Test and improve your memory focus!',
    category: 'Puzzle',
    tags: ['Memory Match', 'Brain Training', 'Cards', 'Time Attack', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #00ff88 0%, #9900ff 100%)',
    accentColor: '#00ff88',
    iconName: 'Grid',
    rating: 4.8,
    plays: 92000,
    orientation: 'portrait',
    engine: 'canvas',
    featured: false,
    trending: false,
    isNew: true,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Easy',
    controls: {
      desktop: ['Click Card: Flip & Match'],
      mobile: ['Tap Card: Flip & Match']
    }
  },
  {
    id: 'neon-wings',
    slug: 'neon-wings',
    title: 'Neon Wings',
    tagline: 'Flap through glowing cyber portals in deep space.',
    description: 'Precision timing wing runner! Tap to flap your cyber wings upward and guide your character through narrow glowing plasma gates.',
    category: 'Arcade',
    tags: ['Wing Flap', 'Precision', 'Arcade', 'Portal Gates', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #ff007f 0%, #00f0ff 100%)',
    accentColor: '#ff007f',
    iconName: 'Sparkles',
    rating: 4.6,
    plays: 68000,
    orientation: 'portrait',
    engine: 'canvas',
    featured: false,
    trending: false,
    isNew: true,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Hard',
    controls: {
      desktop: ['Space Key / Up Arrow / Click: Flap Wings Up'],
      mobile: ['Tap Screen: Flap Wings Up']
    }
  },
  {
    id: 'traffic-rush',
    slug: 'traffic-rush',
    title: 'Traffic Rush 3D',
    tagline: '3D perspective highway lane switcher with nitro speed.',
    description: 'Shift lanes at 200 KM/H on a glowing 3D perspective highway! Dodge oncoming traffic obstacles, trigger nitro boosts, and climb the speed leaderboard.',
    category: 'Racing',
    tags: ['3D Racing', 'Highway', 'Lane Shift', 'Nitro', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #00f0ff 0%, #ff0055 100%)',
    accentColor: '#00f0ff',
    iconName: 'Zap',
    rating: 4.9,
    plays: 125000,
    orientation: 'landscape',
    engine: 'canvas',
    featured: true,
    trending: true,
    isNew: true,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['A / Left Arrow: Shift Left Lane', 'D / Right Arrow: Shift Right Lane', 'Space / W: Nitro Boost'],
      mobile: ['Left Touch Button: Shift Left', 'Right Touch Button: Shift Right', 'BOOST Button: Nitro']
    }
  },
  {
    id: 'color-sort',
    slug: 'color-sort',
    title: 'Color Sort Puzzle',
    tagline: 'Satisfying liquid tube color sorting brain teaser.',
    description: 'Pour colored liquid between test tubes until every tube is filled with a single solid color! Plan your moves carefully and solve progressively harder levels.',
    category: 'Casual',
    tags: ['Color Sort', 'Puzzle', 'Brain Teaser', 'Relaxing', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #ff0055 0%, #00f0ff 100%)',
    accentColor: '#ff0055',
    iconName: 'Smile',
    rating: 4.9,
    plays: 184000,
    orientation: 'portrait',
    engine: 'canvas',
    featured: true,
    trending: true,
    isNew: true,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Easy',
    controls: {
      desktop: ['Click Tube: Select / Pour liquid into destination tube'],
      mobile: ['Tap Tube: Select & Pour colored liquid']
    }
  },
  {
    id: 'dual-arena',
    slug: 'dual-arena',
    title: 'Dual Arena Combat',
    tagline: 'Fast-paced local 2-player arena battle on a single screen.',
    description: 'Face off against a friend on the same device! Dodge incoming plasma shots, aim your lasers, and destroy your rival hero in intense split-screen combat.',
    category: 'Action',
    tags: ['2-Player', 'Local Versus', 'Arena Combat', 'Duels', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #00f0ff 0%, #ff007f 100%)',
    accentColor: '#ff007f',
    iconName: 'Swords',
    rating: 4.8,
    plays: 142000,
    orientation: 'landscape',
    engine: 'canvas',
    featured: true,
    trending: true,
    isNew: true,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['P1: W, A, S, D + Space to Shoot', 'P2: Arrow Keys + Enter to Shoot'],
      mobile: ['P1: Tap Left Side to Shoot', 'P2: Tap Right Side to Shoot']
    }
  },
  {
    id: 'mini-golf',
    slug: 'mini-golf',
    title: 'Neon Mini Golf',
    tagline: 'Precision drag-to-aim mini golf course challenge.',
    description: 'Line up your shots and sink golf balls across neon obstacle courses! Dodge moving barriers, time your power meter, and score under par.',
    category: 'Sports',
    tags: ['Mini Golf', 'Physics', 'Drag Aim', 'Obstacles', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #00ff88 0%, #0088ff 100%)',
    accentColor: '#00ff88',
    iconName: 'Trophy',
    rating: 4.9,
    plays: 156000,
    orientation: 'portrait',
    engine: 'canvas',
    featured: true,
    trending: true,
    isNew: true,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['Click & Drag Ball Backwards: Aim & Adjust Power', 'Release: Shoot Golf Ball'],
      mobile: ['Touch & Drag Ball Backwards: Aim & Adjust Power', 'Release Touch: Shoot Ball']
    }
  },
  {
    id: 'cricket-smash',
    slug: 'cricket-smash',
    title: 'Cricket Smash',
    tagline: 'Mobile-first neon cricket batting challenge.',
    description: 'Timing is everything! Time your shots precisely as bowler delivers speedballs, spin, and yorkers. Smash 4s and 6s across 2 overs!',
    category: 'Sports',
    tags: ['Cricket', 'Batting', 'Timing', 'Sports', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #00ff88 0%, #00f0ff 100%)',
    accentColor: '#00ff88',
    iconName: 'Trophy',
    rating: 4.9,
    plays: 210000,
    orientation: 'portrait',
    engine: 'canvas',
    featured: true,
    trending: true,
    isNew: true,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['Space / Click / Arrow Up: Time Batting Shot'],
      mobile: ['Tap Screen when ball crosses timing line']
    }
  },
  {
    id: 'penalty-shootout',
    slug: 'penalty-shootout',
    title: 'Penalty Shootout',
    tagline: 'Swipe and curve football penalty shots past AI keeper.',
    description: 'Step up to the penalty spot! Swipe and curve precision football shots into top goal corners past an agile goalkeeper.',
    category: 'Sports',
    tags: ['Football', 'Penalty', 'Soccer', 'Sports', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #ff0055 0%, #ffaa00 100%)',
    accentColor: '#ff0055',
    iconName: 'Trophy',
    rating: 4.8,
    plays: 198000,
    orientation: 'portrait',
    engine: 'canvas',
    featured: true,
    trending: true,
    isNew: true,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Easy',
    controls: {
      desktop: ['Click & Drag Ball Upwards to Shoot'],
      mobile: ['Swipe / Drag Ball Upwards toward goal corner']
    }
  }
];

export const CATEGORIES_LIST: Array<{ name: string; slug: string; iconName: string; count: number; bgGradient: string }> = [
  { name: 'Racing', slug: 'racing', iconName: 'Flame', count: 2, bgGradient: 'from-cyan-500 to-blue-600' },
  { name: 'Action', slug: 'action', iconName: 'Swords', count: 3, bgGradient: 'from-pink-500 to-purple-600' },
  { name: 'Puzzle', slug: 'puzzle', iconName: 'Puzzle', count: 3, bgGradient: 'from-emerald-400 to-teal-600' },
  { name: 'Arcade', slug: 'arcade', iconName: 'Gamepad2', count: 2, bgGradient: 'from-violet-500 to-indigo-600' },
  { name: 'Sports', slug: 'sports', iconName: 'Trophy', count: 4, bgGradient: 'from-amber-400 to-orange-600' },
  { name: 'Strategy', slug: 'strategy', iconName: 'Brain', count: 1, bgGradient: 'from-purple-600 to-pink-600' },
  { name: 'Casual', slug: 'casual', iconName: 'Smile', count: 1, bgGradient: 'from-fuchsia-500 to-pink-600' }
];
