import type { GameDefinition } from './types';

export const GAMES_CATALOG: GameDefinition[] = [
  {
    id: 'manu-kart',
    slug: 'manu-kart',
    title: 'Manu Kart',
    tagline: 'Flagship 2D/3D highway kart racing with drift & powerups.',
    description: 'ManuPlay flagship racer! Outmaneuver rival AI karts, hit speed boosters, collect nitro cans, trigger powerups, and set record lap times across futuristic neon tracks.',
    category: 'Racing',
    tags: ['Flagship', 'Kart Racing', 'Drift', 'Nitro', 'Powerups', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #00f0ff 0%, #a855f7 100%)',
    accentColor: '#00f0ff',
    iconName: 'Flame',
    rating: 5.0,
    plays: 285000,
    orientation: 'landscape',
    engine: 'canvas',
    loadEngine: () => import('./manu-kart/ManuKartGame').then(m => m.ManuKartGame),
    featured: true,
    trending: true,
    isNew: true,
    offlineSupported: true,
    multiplayerSupported: true,
    manuCoinsReward: 100,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['A / Left Arrow: Steer Left', 'D / Right Arrow: Steer Right', 'Space / W: Nitro Boost'],
      mobile: ['Left Touch Button: Turn Left', 'Right Touch Button: Turn Right', 'BOOST Button: Nitro']
    }
  },
  {
    id: 'chess',
    slug: 'chess',
    title: 'Chess Master',
    tagline: 'Classic chess with smart AI & local 2-player modes.',
    description: 'Challenge your mind with grandmaster strategy! Play against adaptive AI or duel a friend on the same screen with full move validation, blitz timers, and puzzle challenges.',
    category: 'Board',
    tags: ['Chess', 'Brain', 'AI Opponent', '2 Player', 'Offline', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #1e293b 0%, #475569 100%)',
    accentColor: '#38bdf8',
    iconName: 'Brain',
    rating: 4.9,
    plays: 195000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./chess/ChessGame').then(m => m.ChessGame),
    featured: true,
    trending: true,
    isNew: true,
    offlineSupported: true,
    multiplayerSupported: true,
    manuCoinsReward: 80,
    sessionLength: 'Medium (5-15 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['Click Chess Piece to select and click target square to move'],
      mobile: ['Tap Chess Piece to highlight valid moves and tap destination']
    }
  },
  {
    id: '8ball-pool',
    slug: '8ball-pool',
    title: '8 Ball Pool',
    tagline: 'Realistic physics cue ball pocketing challenge.',
    description: 'Master cue ball trajectory and spin! Drag back to aim, adjust power, and sink target balls into 6 pockets with realistic cushion reflection physics.',
    category: 'Sports',
    tags: ['Pool', 'Physics', 'Billiards', 'Aim Line', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #059669 0%, #064e3b 100%)',
    accentColor: '#10b981',
    iconName: 'Trophy',
    rating: 4.9,
    plays: 230000,
    orientation: 'landscape',
    engine: 'canvas',
    loadEngine: () => import('./8ball-pool/EightBallPoolGame').then(m => m.EightBallPoolGame),
    featured: true,
    trending: true,
    isNew: true,
    offlineSupported: true,
    multiplayerSupported: true,
    manuCoinsReward: 90,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['Click & Drag mouse backward from cue ball to aim and release to shoot'],
      mobile: ['Touch & Drag backward to adjust aim angle & power meter, then release']
    }
  },
  {
    id: 'trivia-battle',
    slug: 'trivia-battle',
    title: 'Trivia Battle',
    tagline: 'Real-time quiz across Gaming, Science, Tech & Sports.',
    description: 'Test your knowledge against the clock! Answer questions across popular categories, build answer streak multipliers, and earn massive XP rewards.',
    category: 'Trivia',
    tags: ['Quiz', 'Trivia', 'Brain Training', 'Streak Multiplier', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #f59e0b 0%, #ec4899 100%)',
    accentColor: '#f59e0b',
    iconName: 'Sparkles',
    rating: 4.8,
    plays: 162000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./trivia-battle/TriviaBattleGame').then(m => m.TriviaBattleGame),
    featured: true,
    trending: true,
    isNew: true,
    offlineSupported: true,
    multiplayerSupported: false,
    manuCoinsReward: 75,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Easy',
    controls: {
      desktop: ['Click option buttons A, B, C, D before the timer runs out'],
      mobile: ['Tap answer buttons A, B, C, D before time expires']
    }
  },
  {
    id: 'neon-drift',
    slug: 'neon-drift',
    title: 'Neon Drift',
    tagline: 'High-speed cyberpunk highway racing with instant nitro boosts.',
    description: 'Hit the neon-drenched highway at night! Dodge speeding traffic, collect energy power-ups, boost through speed traps, and see how long you can survive the endless drift.',
    category: 'Racing',
    tags: ['Cyberpunk', 'High Speed', 'Nitro', 'Highway', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #00f0ff 0%, #7000ff 100%)',
    accentColor: '#00f0ff',
    iconName: 'Zap',
    rating: 4.9,
    plays: 142500,
    orientation: 'landscape',
    engine: 'canvas',
    loadEngine: () => import('./neon-drift/NeonDriftGame').then(m => m.NeonDriftGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 50,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['A / Left Arrow: Turn Left', 'D / Right Arrow: Turn Right', 'Space / W: Nitro Boost', 'S / Down: Brake'],
      mobile: ['Left Touch Button: Turn Left', 'Right Touch Button: Turn Right', 'BOOST Button: Nitro Speed', 'BRAKE Button: Slow down']
    }
  },
  {
    id: 'sky-runner',
    slug: 'sky-runner',
    title: 'Sky Runner',
    tagline: 'Leap across cyber platforms high above the clouds.',
    description: 'Precision endless platform runner set in a glowing futuristic skyline. Time your jumps and double jumps to scale floating platforms, collect plasma orbs, and avoid laser spikes!',
    category: 'Action',
    tags: ['Endless Runner', 'Platforms', 'Double Jump', 'Cyberpunk', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #ff007f 0%, #7928ca 100%)',
    accentColor: '#ff007f',
    iconName: 'Sparkles',
    rating: 4.8,
    plays: 98400,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./sky-runner/SkyRunnerGame').then(m => m.SkyRunnerGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 50,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['Space / W / Up Arrow: Jump (Press again for Double Jump)'],
      mobile: ['Tap Screen / JUMP Button: Jump & Double Jump']
    }
  },
  {
    id: 'zombie-survival',
    slug: 'zombie-survival',
    title: 'Zombie Survival',
    tagline: 'Top-down neon wave survival shooter.',
    description: 'Survive relentless waves of neon cyber-zombies in a localized arena! Move swiftly, manage your ammunition, collect health medkits, and clear every wave before you get overwhelmed.',
    category: 'Action',
    tags: ['Survival', 'Shooter', 'Zombie Waves', 'Arena', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #ffaa00 0%, #ff0055 100%)',
    accentColor: '#ffaa00',
    iconName: 'ShieldAlert',
    rating: 4.7,
    plays: 112000,
    orientation: 'landscape',
    engine: 'canvas',
    loadEngine: () => import('./zombie-survival/ZombieSurvivalGame').then(m => m.ZombieSurvivalGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 60,
    sessionLength: 'Medium (5-15 min)',
    difficulty: 'Hard',
    controls: {
      desktop: ['W, A, S, D / Arrows: Move character', 'Space / Left Click: Fire Laser Weapon'],
      mobile: ['Left Virtual Joystick / DPAD: Move', 'FIRE Touch Button: Shoot Laser']
    }
  },
  {
    id: 'block-puzzle',
    slug: 'block-puzzle',
    title: 'Block Puzzle',
    tagline: 'Addictive grid block placement & line clears.',
    description: 'Place geometric neon blocks on an 8x8 grid to complete full horizontal rows and vertical columns. Clear multiple lines simultaneously for massive combo multipliers!',
    category: 'Puzzle',
    tags: ['Grid Puzzle', 'Brain Teaser', 'Combo Clear', 'Relaxing', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #00ff88 0%, #0088ff 100%)',
    accentColor: '#00ff88',
    iconName: 'Grid',
    rating: 4.9,
    plays: 210000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./block-puzzle/BlockPuzzleGame').then(m => m.BlockPuzzleGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 40,
    sessionLength: 'Medium (5-15 min)',
    difficulty: 'Easy',
    controls: {
      desktop: ['Click & Drag Block: Place on Grid'],
      mobile: ['Touch Drag Block: Place on Grid cell']
    }
  },
  {
    id: 'space-shooter',
    slug: 'space-shooter',
    title: 'Space Shooter',
    tagline: 'Classic horizontal arcade galaxy defender.',
    description: 'Take command of the starship Alpha-1! Pilot through asteroid belts, destroy alien fighter squadrons, grab weapon upgrade power-ups, and defeat colossal mothership bosses.',
    category: 'Arcade',
    tags: ['Space Combat', 'Shmup', 'Boss Battles', 'Powerups', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #9900ff 0%, #00e5ff 100%)',
    accentColor: '#00e5ff',
    iconName: 'Rocket',
    rating: 4.8,
    plays: 165000,
    orientation: 'landscape',
    engine: 'canvas',
    loadEngine: () => import('./space-shooter/SpaceShooterGame').then(m => m.SpaceShooterGame),
    featured: false,
    trending: false,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 50,
    sessionLength: 'Medium (5-15 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['W, A, S, D / Arrow Keys: Move Ship', 'Space Key: Auto/Manual Laser Fire'],
      mobile: ['Touch & Drag Ship / Virtual Stick: Move & Shoot']
    }
  },
  {
    id: 'tower-defense',
    slug: 'tower-defense',
    title: 'Tower Defense',
    tagline: 'Strategic tactical defense against cyber creep waves.',
    description: 'Build and upgrade Laser Turrets, Plasma Cannons, and Frost Towers along the creep path to defend your central core. Manage your gold economy and survive boss waves!',
    category: 'Strategy',
    tags: ['Tower Defense', 'Strategy', 'Turrets', 'Creep Waves', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #7000ff 0%, #ff007f 100%)',
    accentColor: '#7000ff',
    iconName: 'ShieldAlert',
    rating: 4.9,
    plays: 87000,
    orientation: 'landscape',
    engine: 'canvas',
    loadEngine: () => import('./tower-defense/TowerDefenseGame').then(m => m.TowerDefenseGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 70,
    sessionLength: 'Long (15+ min)',
    difficulty: 'Hard',
    controls: {
      desktop: ['Click Road Grid Cell: Place Tower', 'Select Tower Type: Bottom Toolbar'],
      mobile: ['Tap Road Grid Cell: Place Tower', 'Tap Toolbar: Select Tower Type']
    }
  },
  {
    id: 'hoop-master',
    slug: 'hoop-master',
    title: 'Hoop Master',
    tagline: 'Precision basketball shooting & streak combo challenges.',
    description: 'Adjust your launch trajectory and shoot basketballs into moving hoops. Chain swish shots to multiply your streak bonus and earn extra shots!',
    category: 'Sports',
    tags: ['Basketball', 'Physics', 'Shooting', 'Streak Combo', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #ff6600 0%, #ffaa00 100%)',
    accentColor: '#ff6600',
    iconName: 'Trophy',
    rating: 4.7,
    plays: 74000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./hoop-master/HoopMasterGame').then(m => m.HoopMasterGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 40,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Easy',
    controls: {
      desktop: ['Up / Down Arrows: Adjust Trajectory Angle', 'Space Key / Click: Shoot Ball'],
      mobile: ['Tap Screen: Shoot Ball towards Target']
    }
  },
  {
    id: 'cyber-memory',
    slug: 'cyber-memory',
    title: 'Cyber Memory',
    tagline: 'Brain training icon matching against the clock.',
    description: 'Flip glowing neon cards to match identical cyber icons on a 4x4 grid before time runs out. Test and improve your memory focus!',
    category: 'Puzzle',
    tags: ['Memory Match', 'Brain Training', 'Cards', 'Time Attack', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #00ff88 0%, #9900ff 100%)',
    accentColor: '#00ff88',
    iconName: 'Grid',
    rating: 4.8,
    plays: 92000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./cyber-memory/CyberMemoryGame').then(m => m.CyberMemoryGame),
    featured: false,
    trending: false,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 35,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Easy',
    controls: {
      desktop: ['Click Card: Flip & Match'],
      mobile: ['Tap Card: Flip & Match']
    }
  },
  {
    id: 'neon-wings',
    slug: 'neon-wings',
    title: 'Neon Wings',
    tagline: 'Flap through glowing cyber portals in deep space.',
    description: 'Precision timing wing runner! Tap to flap your cyber wings upward and guide your character through narrow glowing plasma gates.',
    category: 'Arcade',
    tags: ['Wing Flap', 'Precision', 'Arcade', 'Portal Gates', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #ff007f 0%, #00f0ff 100%)',
    accentColor: '#ff007f',
    iconName: 'Sparkles',
    rating: 4.6,
    plays: 68000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./neon-wings/NeonWingsGame').then(m => m.NeonWingsGame),
    featured: false,
    trending: false,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 40,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Hard',
    controls: {
      desktop: ['Space Key / Up Arrow / Click: Flap Wings Up'],
      mobile: ['Tap Screen: Flap Wings Up']
    }
  },
  {
    id: 'traffic-rush',
    slug: 'traffic-rush',
    title: 'Traffic Rush 3D',
    tagline: '3D perspective highway lane switcher with nitro speed.',
    description: 'Shift lanes at 200 KM/H on a glowing 3D perspective highway! Dodge oncoming traffic obstacles, trigger nitro boosts, and climb the speed leaderboard.',
    category: 'Racing',
    tags: ['3D Racing', 'Highway', 'Lane Shift', 'Nitro', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #00f0ff 0%, #ff0055 100%)',
    accentColor: '#00f0ff',
    iconName: 'Zap',
    rating: 4.9,
    plays: 125000,
    orientation: 'landscape',
    engine: 'canvas',
    loadEngine: () => import('./traffic-rush/TrafficRushGame').then(m => m.TrafficRushGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 50,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['A / Left Arrow: Shift Left Lane', 'D / Right Arrow: Shift Right Lane', 'Space / W: Nitro Boost'],
      mobile: ['Left Touch Button: Shift Left', 'Right Touch Button: Shift Right', 'BOOST Button: Nitro']
    }
  },
  {
    id: 'color-sort',
    slug: 'color-sort',
    title: 'Color Sort Puzzle',
    tagline: 'Satisfying liquid tube color sorting brain teaser.',
    description: 'Pour colored liquid between test tubes until every tube is filled with a single solid color! Plan your moves carefully and solve progressively harder levels.',
    category: 'Casual',
    tags: ['Color Sort', 'Puzzle', 'Brain Teaser', 'Relaxing', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #ff0055 0%, #00f0ff 100%)',
    accentColor: '#ff0055',
    iconName: 'Smile',
    rating: 4.9,
    plays: 184000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./color-sort/ColorSortGame').then(m => m.ColorSortGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 35,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Easy',
    controls: {
      desktop: ['Click Tube: Select / Pour liquid into destination tube'],
      mobile: ['Tap Tube: Select & Pour colored liquid']
    }
  },
  {
    id: 'dual-arena',
    slug: 'dual-arena',
    title: 'Dual Arena Combat',
    tagline: 'Fast-paced local 2-player arena battle on a single screen.',
    description: 'Face off against a friend on the same device! Dodge incoming plasma shots, aim your lasers, and destroy your rival hero in intense split-screen combat.',
    category: '2 Player',
    tags: ['2-Player', 'Local Versus', 'Arena Combat', 'Duels', 'Landscape'],
    thumbnailBg: 'linear-gradient(135deg, #00f0ff 0%, #ff007f 100%)',
    accentColor: '#ff007f',
    iconName: 'Swords',
    rating: 4.8,
    plays: 142000,
    orientation: 'landscape',
    engine: 'canvas',
    loadEngine: () => import('./dual-arena/DualArenaGame').then(m => m.DualArenaGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    multiplayerSupported: true,
    manuCoinsReward: 60,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['P1: W, A, S, D + Space to Shoot', 'P2: Arrow Keys + Enter to Shoot'],
      mobile: ['P1: Tap Left Side to Shoot', 'P2: Tap Right Side to Shoot']
    }
  },
  {
    id: 'mini-golf',
    slug: 'mini-golf',
    title: 'Neon Mini Golf',
    tagline: 'Precision drag-to-aim mini golf course challenge.',
    description: 'Line up your shots and sink golf balls across neon obstacle courses! Dodge moving barriers, time your power meter, and score under par.',
    category: 'Sports',
    tags: ['Mini Golf', 'Physics', 'Drag Aim', 'Obstacles', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #00ff88 0%, #0088ff 100%)',
    accentColor: '#00ff88',
    iconName: 'Trophy',
    rating: 4.9,
    plays: 156000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./mini-golf/MiniGolfGame').then(m => m.MiniGolfGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 45,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['Click & Drag Ball Backwards: Aim & Adjust Power', 'Release: Shoot Golf Ball'],
      mobile: ['Touch & Drag Ball Backwards: Aim & Adjust Power', 'Release Touch: Shoot Ball']
    }
  },
  {
    id: 'cricket-smash',
    slug: 'cricket-smash',
    title: 'Cricket Smash',
    tagline: 'Mobile-first neon cricket batting challenge.',
    description: 'Timing is everything! Time your shots precisely as bowler delivers speedballs, spin, and yorkers. Smash 4s and 6s across 2 overs!',
    category: 'Sports',
    tags: ['Cricket', 'Batting', 'Timing', 'Sports', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #00ff88 0%, #00f0ff 100%)',
    accentColor: '#00ff88',
    iconName: 'Trophy',
    rating: 4.9,
    plays: 210000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./cricket-smash/CricketSmashGame').then(m => m.CricketSmashGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 50,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Medium',
    controls: {
      desktop: ['Space / Click / Arrow Up: Time Batting Shot'],
      mobile: ['Tap Screen when ball crosses timing line']
    }
  },
  {
    id: 'penalty-shootout',
    slug: 'penalty-shootout',
    title: 'Penalty Shootout',
    tagline: 'Swipe and curve football penalty shots past AI keeper.',
    description: 'Step up to the penalty spot! Swipe and curve precision football shots into top goal corners past an agile goalkeeper.',
    category: 'Sports',
    tags: ['Football', 'Penalty', 'Soccer', 'Sports', 'Portrait'],
    thumbnailBg: 'linear-gradient(135deg, #ff0055 0%, #ffaa00 100%)',
    accentColor: '#ff0055',
    iconName: 'Trophy',
    rating: 4.8,
    plays: 198000,
    orientation: 'portrait',
    engine: 'canvas',
    loadEngine: () => import('./penalty-shootout/PenaltyShootoutGame').then(m => m.PenaltyShootoutGame),
    featured: false,
    trending: true,
    isNew: false,
    offlineSupported: true,
    manuCoinsReward: 45,
    sessionLength: 'Quick (2-5 min)',
    difficulty: 'Easy',
    controls: {
      desktop: ['Click & Drag Ball Upwards to Shoot'],
      mobile: ['Swipe / Drag Ball Upwards toward goal corner']
    }
  }
];

export const CATEGORIES_LIST: Array<{ name: string; slug: string; iconName: string; count: number; bgGradient: string }> = [
  { name: 'Racing', slug: 'racing', iconName: 'Flame', count: 3, bgGradient: 'from-cyan-500 to-blue-600' },
  { name: 'Action', slug: 'action', iconName: 'Swords', count: 2, bgGradient: 'from-pink-500 to-purple-600' },
  { name: 'Puzzle', slug: 'puzzle', iconName: 'Puzzle', count: 2, bgGradient: 'from-emerald-400 to-teal-600' },
  { name: 'Sports', slug: 'sports', iconName: 'Trophy', count: 5, bgGradient: 'from-amber-400 to-orange-600' },
  { name: 'Board', slug: 'board', iconName: 'Brain', count: 1, bgGradient: 'from-indigo-500 to-purple-600' },
  { name: 'Trivia', slug: 'trivia', iconName: 'Sparkles', count: 1, bgGradient: 'from-fuchsia-500 to-pink-600' },
  { name: '2 Player', slug: '2-player', iconName: 'Swords', count: 2, bgGradient: 'from-purple-600 to-pink-600' },
  { name: 'Arcade', slug: 'arcade', iconName: 'Gamepad2', count: 2, bgGradient: 'from-violet-500 to-indigo-600' },
  { name: 'Strategy', slug: 'strategy', iconName: 'Brain', count: 1, bgGradient: 'from-purple-600 to-pink-600' },
  { name: 'Casual', slug: 'casual', iconName: 'Smile', count: 1, bgGradient: 'from-fuchsia-500 to-pink-600' }
];
